import {
  FaHouse,
  FaServer,
  FaShieldHalved,
  FaMobileScreenButton,
  FaGear,
  FaBolt,
  FaScaleBalanced,
  FaUserSecret,
  FaGlobe,
  FaComment,
  FaChartLine,
  FaVideo,
  FaPrint,
  FaBuildingColumns,
  FaRectangleAd,
  FaSatelliteDish,
  FaBug,
  FaPowerOff,
  FaArrowsRotate,
  FaWifi,
  FaSignal,
  FaGaugeHigh,
  FaUser,
  FaDoorOpen,
  FaDoorClosed,
  FaWaveSquare,
  FaTriangleExclamation,
  FaDownload,
  FaUpload,
  FaCircleCheck,
  FaCircleXmark,
  FaBan,
  FaCircleQuestion,
  FaBell,
  FaHeadset,
  FaLock,
  FaBugSlash,
  FaShuffle,
  FaRoute,
  FaFingerprint,
  FaCrown,
  FaChevronLeft,
  FaChevronRight,
  FaStar,
  FaRegStar,
  FaMagnifyingGlass,
  FaPlus,
  FaTrash,
  FaCheck,
  FaArrowRotateRight,
  FaWandMagicSparkles,
  FaCircleInfo,
  FaClock,
  FaXmark,
} from "react-icons/fa6";
import type { IconType } from "react-icons";
import type { IconName } from "@/lib/data";

const SOLID: Record<IconName, IconType> = {
  house: FaHouse,
  server: FaServer,
  "shield-halved": FaShieldHalved,
  "mobile-screen-button": FaMobileScreenButton,
  gear: FaGear,
  bolt: FaBolt,
  "scale-balanced": FaScaleBalanced,
  "user-secret": FaUserSecret,
  globe: FaGlobe,
  comment: FaComment,
  "chart-line": FaChartLine,
  video: FaVideo,
  print: FaPrint,
  "building-columns": FaBuildingColumns,
  "rectangle-ad": FaRectangleAd,
  "satellite-dish": FaSatelliteDish,
  bug: FaBug,
  "power-off": FaPowerOff,
  "arrows-rotate": FaArrowsRotate,
  wifi: FaWifi,
  signal: FaSignal,
  "gauge-high": FaGaugeHigh,
  user: FaUser,
  "door-open": FaDoorOpen,
  "door-closed": FaDoorClosed,
  "wave-square": FaWaveSquare,
  "triangle-exclamation": FaTriangleExclamation,
  download: FaDownload,
  upload: FaUpload,
  "circle-check": FaCircleCheck,
  "circle-xmark": FaCircleXmark,
  ban: FaBan,
  "circle-question": FaCircleQuestion,
  bell: FaBell,
  headset: FaHeadset,
  lock: FaLock,
  "bug-slash": FaBugSlash,
  shuffle: FaShuffle,
  route: FaRoute,
  fingerprint: FaFingerprint,
  crown: FaCrown,
  "chevron-left": FaChevronLeft,
  "chevron-right": FaChevronRight,
  star: FaStar,
  "magnifying-glass": FaMagnifyingGlass,
  plus: FaPlus,
  trash: FaTrash,
  check: FaCheck,
  "arrow-rotate-right": FaArrowRotateRight,
  "wand-magic-sparkles": FaWandMagicSparkles,
  "circle-info": FaCircleInfo,
  clock: FaClock,
  xmark: FaXmark,
};

export default function Icon({
  name,
  variant = "solid",
  size = 16,
  color,
  className,
  style,
}: {
  name: IconName;
  variant?: "solid" | "regular";
  size?: number;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Component = variant === "regular" && name === "star" ? FaRegStar : SOLID[name];
  return <Component size={size} color={color} className={className} style={style} />;
}
